name: Bundle Analysis

on:
  pull_request:
    branches: [main]

jobs:
  analyze-bundle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Build and analyze
        run: |
          npm run build:analyze
          test -f bundle-report.html

      - name: Upload bundle report
        uses: actions/upload-artifact@v4
        with:
          name: bundle-report
          path: bundle-report.html

      - name: Measure bundle size
        id: size-limit
        run: |
          OUTPUT=$(npm run size-limit -- --json)
          echo "$OUTPUT"
          {
            echo "json<<'EOF'"
            echo "$OUTPUT"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Comment bundle size
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          SIZE_LIMIT_JSON: ${{ steps.size-limit.outputs.json }}
        with:
          script: |
            const results = JSON.parse(process.env.SIZE_LIMIT_JSON);
            const body = [
              '### Bundle Size Report',
              '',
              ...results.map(result => `- **${result.name}**: ${result.size} (limit: ${result.limit})`)
            ].join('\n');

            const { context, github } = require('@actions/github');
            const params = {
              ...context.repo,
              issue_number: context.issue.number,
              body
            };

            await github.rest.issues.createComment(params);
